CREATE TABLE consultation
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date        TIMESTAMP WITHOUT TIME ZONE,
    motif       VARCHAR(255),
    rapport     VARCHAR(255),
    currentdate TIMESTAMP WITHOUT TIME ZONE,
    updatedate  TIMESTAMP WITHOUT TIME ZONE,
    medecin_id  INTEGER,
    patient_id  INTEGER,
    dossier_id  BIGINT,
    CONSTRAINT pk_consultation PRIMARY KEY (id)
);

CREATE TABLE diagnosticia
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date        TIMESTAMP WITHOUT TIME ZONE,
    symptomes   VARCHAR(255),
    resultat    VARCHAR(255),
    currentdate TIMESTAMP WITHOUT TIME ZONE,
    updatedate  TIMESTAMP WITHOUT TIME ZONE,
    patient_id  INTEGER,
    CONSTRAINT pk_diagnosticia PRIMARY KEY (id)
);

CREATE TABLE document_medical
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nom             VARCHAR(255),
    type            VARCHAR(255),
    currentdate     TIMESTAMP WITHOUT TIME ZONE,
    updatedate      TIMESTAMP WITHOUT TIME ZONE,
    consultation_id BIGINT,
    CONSTRAINT pk_documentmedical PRIMARY KEY (id)
);

CREATE TABLE dossier_medical
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    currentdate TIMESTAMP WITHOUT TIME ZONE,
    updatedate  TIMESTAMP WITHOUT TIME ZONE,
    patient_id  INTEGER,
    CONSTRAINT pk_dossiermedical PRIMARY KEY (id)
);

CREATE TABLE rendez_vous
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date        TIMESTAMP WITHOUT TIME ZONE,
    statut      VARCHAR(255),
    raison      VARCHAR(255),
    currentdate TIMESTAMP WITHOUT TIME ZONE,
    updatedate  TIMESTAMP WITHOUT TIME ZONE,
    medecin_id  INTEGER,
    patient_id  INTEGER,
    CONSTRAINT pk_rendezvous PRIMARY KEY (id)
);

CREATE TABLE specialite
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nom         VARCHAR(255),
    description VARCHAR(255),
    currentdate TIMESTAMP WITHOUT TIME ZONE,
    updatedate  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_specialite PRIMARY KEY (id)
);

CREATE TABLE utilisateur
(
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nom            VARCHAR(255),
    prenom         VARCHAR(255),
    date_naissance date,
    sexe           VARCHAR(255),
    telephone      VARCHAR(255),
    adresse        VARCHAR(255),
    cin            VARCHAR(255),
    photo_profil   VARCHAR(255),
    currentdate    TIMESTAMP WITHOUT TIME ZONE,
    updatedate     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_utilisateur PRIMARY KEY (id)
);

ALTER TABLE dossier_medical
    ADD CONSTRAINT uc_dossiermedical_patient UNIQUE (patient_id);

ALTER TABLE administrateur
    ADD CONSTRAINT FK_ADMINISTRATEUR_ON_ID FOREIGN KEY (id) REFERENCES utilisateur (id);

ALTER TABLE assistante
    ADD CONSTRAINT FK_ASSISTANTE_ON_ID FOREIGN KEY (id) REFERENCES utilisateur (id);

ALTER TABLE compte
    ADD CONSTRAINT FK_COMPTE_ON_UTILISATEUR FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id);

ALTER TABLE consultation
    ADD CONSTRAINT FK_CONSULTATION_ON_DOSSIER FOREIGN KEY (dossier_id) REFERENCES dossier_medical (id);

ALTER TABLE consultation
    ADD CONSTRAINT FK_CONSULTATION_ON_MEDECIN FOREIGN KEY (medecin_id) REFERENCES medecin (id);

ALTER TABLE consultation
    ADD CONSTRAINT FK_CONSULTATION_ON_PATIENT FOREIGN KEY (patient_id) REFERENCES patient (id);

ALTER TABLE diagnosticia
    ADD CONSTRAINT FK_DIAGNOSTICIA_ON_PATIENT FOREIGN KEY (patient_id) REFERENCES patient (id);

ALTER TABLE document_medical
    ADD CONSTRAINT FK_DOCUMENTMEDICAL_ON_CONSULTATION FOREIGN KEY (consultation_id) REFERENCES consultation (id);

ALTER TABLE dossier_medical
    ADD CONSTRAINT FK_DOSSIERMEDICAL_ON_PATIENT FOREIGN KEY (patient_id) REFERENCES patient (id);

ALTER TABLE medecin
    ADD CONSTRAINT FK_MEDECIN_ON_ID FOREIGN KEY (id) REFERENCES utilisateur (id);

ALTER TABLE medecin
    ADD CONSTRAINT FK_MEDECIN_ON_SPECIALITE FOREIGN KEY (specialite_id) REFERENCES specialite (id);

ALTER TABLE patient
    ADD CONSTRAINT FK_PATIENT_ON_ID FOREIGN KEY (id) REFERENCES utilisateur (id);

ALTER TABLE rendez_vous
    ADD CONSTRAINT FK_RENDEZVOUS_ON_MEDECIN FOREIGN KEY (medecin_id) REFERENCES medecin (id);

ALTER TABLE rendez_vous
    ADD CONSTRAINT FK_RENDEZVOUS_ON_PATIENT FOREIGN KEY (patient_id) REFERENCES patient (id);